version: '3.8'

services:
  db:
    image: postgis/postgis:12-3.1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: todoapp
      POSTGRES_USER: todoappuser
      POSTGRES_PASSWORD: pass
    ports:
      - "8002:5432"
    networks:
      - djangonetwork
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U todoappuser -d todoapp'"]
      interval: 10s
      timeout: 3s
      retries: 3

  web:
    build: 
      dockerfile: docker/Dockerfile
    command: >
      sh -c "
      python manage.py migrate;
      python manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/todo_site
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db:db
    networks:
      - djangonetwork
    environment:
      PGDATABASE: todoapp
      PGUSER: todoappuser
      PGPASSWORD: pass
      PGHOST: db
      PGPORT: 5432
      DJANGO_SETTINGS_MODULE: todo_site.settings.local
      OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY} 

volumes:
  postgres_data:

networks:
  djangonetwork:
    driver: bridge
